name: 'Setup Test Environment'
description: 'Sets up the test environment'

inputs:
  installBWCLI:
    description: 'Install Bitwarden CLI'
    required: false
    default: 'false'
    type: boolean
  bwcliVersion:
    description: 'Version of Bitwarden CLI to install'
    required: false
    default: '2025.2.0'
    type: string
  installBWSCLI:
    description: 'Install Bitwarden Secrets CLI'
    required: false
    default: 'false'
    type: boolean
  bwscliVersion:
    description: 'Version of Bitwarden Secrets CLI to install'
    required: false
    default: '1.0.0'
    type: string
  goVersion:
    description: 'Version of Go to install'
    required: false
    default: '1.24.0'
    type: string
  nodeVersion:
    description: 'Version of Node.js to install'
    required: false
    default: '23.x'
    type: string
  terraformVersion:
    description: 'Version of Terraform to install'
    required: false
    default: '1.11.4'
    type: string
  openTofuVersion:
    description: 'Version of OpenTofu to install'
    required: false
    default: 'v1.9.0'
    type: string
  deviceIdentifier:
    description: 'Device Identifier'
    required: false
    type: string

runs:
  using: "composite"
  steps:
      - id: go-cache-paths
        shell: bash
        run: |
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=${{ inputs.goVersion }}"

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.GOCACHE }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Setup Node.js
        if: ${{ inputs.installCLI }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.openTofuVersion }}

      - name: Set Terraform Version
        shell: bash
        run: |
          echo TF_ACC_TERRAFORM_PATH=$(which tofu) >> $GITHUB_OUTPUT
          echo TF_ACC_PROVIDER_NAMESPACE="hashicorp" >> $GITHUB_OUTPUT
          echo TF_ACC_PROVIDER_HOST="registry.opentofu.org" >> $GITHUB_OUTPUT


      - name: Install Bitwarden CLI
        if: ${{ inputs.installBWCLI }}
        shell: bash
        run: |
          npm install -g @bitwarden/cli@${{ inputs.bwcliVersion }}

      - name: Install BWS CLI
        if: ${{ inputs.installBWSCLI }}
        shell: bash
        run: |
          wget https://github.com/bitwarden/sdk-sm/releases/download/bws-v${{ inputs.bwscliVersion }}/bws-aarch64-unknown-linux-gnu-${{ inputs.bwscliVersion }}.zip -O /usr/local/bin/bws
          chmod +x /usr/local/bin/bws

      - name: Install Mage
        shell: bash
        run: |
          go install github.com/magefile/mage@v1.15.0

      - name: Store Device Identifier
        if: ${{ inputs.deviceIdentifier }}
        shell: bash
        run: |
          mkdir -p ./internal/provider/.bitwarden
          echo -ne "${{ inputs.deviceIdentifier }}" > ./internal/provider/.bitwarden/device_identifier

