name: 'Setup Test Environment'
description: 'Sets up the test environment'

inputs:
  installBWCLI:
    description: 'Install Bitwarden CLI'
    required: false
    default: 'false'
    type: boolean
  bwcliVersion:
    description: 'Version of Bitwarden CLI to install'
    required: false
    default: '2025.2.0'
    type: string
  installBWSCLI:
    description: 'Install Bitwarden Secrets CLI'
    required: false
    default: 'false'
    type: boolean
  bwscliVersion:
    description: 'Version of Bitwarden Secrets CLI to install'
    required: false
    default: '1.0.0'
    type: string
  goVersion:
    description: 'Version of Go to install'
    required: false
    default: '1.24.0'
    type: string
  nodeVersion:
    description: 'Version of Node.js to install'
    required: false
    default: '23.x'
    type: string
  openTofuVersion:
    description: 'Version of OpenTofu to install'
    required: false
    default: 'v1.9.0'
    type: string
  deviceIdentifier:
    description: 'Device Identifier'
    required: false
    type: string

runs:
  using: "composite"
  steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=${{ inputs.goVersion }}"
          cache: true

      - name: Setup Node.js
        if: ${{ inputs.installBWCLI }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ inputs.openTofuVersion }}

      - name: Install Bitwarden CLI
        if: ${{ inputs.installBWCLI }}
        shell: bash
        run: |
          npm install -g @bitwarden/cli@${{ inputs.bwcliVersion }}

      - name: Install BWS CLI
        if: ${{ inputs.installBWSCLI }}
        shell: bash
        run: |
          wget https://github.com/bitwarden/sdk-sm/releases/download/bws-v${{ inputs.bwscliVersion }}/bws-x86_64-unknown-linux-gnu-${{ inputs.bwscliVersion }}.zip -O /tmp/bws.zip
          unzip /tmp/bws.zip -d /tmp/
          mv /tmp/bws /usr/local/bin/bws
          chmod +x /usr/local/bin/bws
          /usr/local/bin/bws --version

      - name: Install Mage
        shell: bash
        run: |
          go install github.com/magefile/mage@v1.15.0

      - name: Store Device Identifier
        if: ${{ inputs.deviceIdentifier }}
        shell: bash
        run: |
          mkdir -p ./internal/provider/.bitwarden
          echo -ne "${{ inputs.deviceIdentifier }}" > ./internal/provider/.bitwarden/device_identifier

