name: CLI Client with Vaultwarden Servers

on:
  push:
    branches: [main]
    paths:
      - "tools/**"
      - "internal/**"
      - "*.go"
      - "go.*"
  pull_request:
    branches: [main]
    paths:
      - "tools/**"
      - "internal/**"
      - "*.go"
      - "go.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      vaultwarden:
        image: vaultwarden/server:1.32.5
        env:
          ADMIN_TOKEN: test1234
          I_REALLY_WANT_VOLATILE_STORAGE: "true"
          DISABLE_ICON_DOWNLOAD: "true"
          LOGIN_RATELIMIT_SECONDS: "1"
          LOGIN_RATELIMIT_MAX_BURST: "1000000"
          ADMIN_RATELIMIT_SECONDS: "1"
          ADMIN_RATELIMIT_MAX_BURST: "1000000"
          DOMAIN: http://127.0.0.1:8000
          ROCKET_PORT: 8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/"
          --health-interval 600s
          --health-timeout 10s
          --health-retries 10
          --health-start-period 15s
          --health-start-interval 6s
        ports:
          - 8000:8000
        volumes:
          - /dev/shm/vaultwarden-data:/data
      nginx:
        image: maxlaverse/nginx-vaultwarden
        ports:
          - 8080:8080
        options: >-
          --link vaultwarden

    steps:
      - id: go-cache-paths
        run: |
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - id: binaries
        run: |
          echo "LOCAL_BINARIES=$GITHUB_WORKSPACE/bin" >> $GITHUB_OUTPUT
          echo "BWCLI_VERSION=2025.2.0" >> $GITHUB_OUTPUT

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24.0"

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.GOCACHE }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x

      - name: Install Bitwarden CLI
        run: |
          npm install -g @bitwarden/cli@${{ steps.binaries.outputs.BWCLI_VERSION }}

      - name: Test with Official Client
        run: go test -coverprofile=profile.cov -timeout 3600s -failfast -v -coverpkg=./... ./...  --tags integration
        env:
          TEST_BACKEND: "vaultwarden"
          TEST_PROVIDER_SERVER_URL: "http://127.0.0.1:8000"
          TEST_PROVIDER_REVERSE_PROXY_URL: "http://127.0.0.1:8080"
          TF_ACC: "1"
